In [4]:
import pandas as pd
CSV_PATH = "cleaned_data.csv"
df = pd.read_csv(CSV_PATH)

C:\Users\kirya\AppData\Local\Temp\ipykernel_28504\1453425465.py:3: DtypeWarning: Columns (0,12,13,14) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(CSV_PATH)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 482238 entries, 0 to 482237
Data columns (total 15 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   territory_code  482238 non-null  object
 1   territory_name  482237 non-null  object
 2   arrival_date    482237 non-null  object
 3   trip_type       482237 non-null  object
 4   visit_type      482237 non-null  object
 5   home_country    482237 non-null  object
 6   home_region     479143 non-null  object
 7   home_city       320349 non-null  object
 8   goal            482237 non-null  object
 9   gender          478082 non-null  object
 10  age_group       478082 non-null  object
 11  income_group    478082 non-null  object
 12  days_cnt        482237 non-null  object
 13  visitors_cnt    482237 non-null  object
 14  spent_mln       478082 non-null  object
dtypes: object(15)
memory usage: 55.2+ MB

In [6]:
print(df.isnull().sum())

territory_code         0
territory_name         1
arrival_date           1
trip_type              1
visit_type             1
home_country           1
home_region         3095
home_city         161889
goal                   1
gender              4156
age_group           4156
income_group        4156
days_cnt               1
visitors_cnt           1
spent_mln           4156
dtype: int64

In [7]:
df

,territory_code,territory_name,arrival_date,trip_type,visit_type,home_country,home_region,home_city,goal,gender,age_group,income_group,days_cnt,visitors_cnt,spent_mln
0,22701000,город Нижний Новгород,2021-01-19,Поездка внутри страны,Турист,Россия,Нижегородская область,Сосновский муниципальный район,Туризм,женский,от 25 до 34 лет,от 30 до 50 тыс. руб.,18,4,0.136508
1,22701000,город Нижний Новгород,2021-01-02,Поездка внутри страны,Турист,Россия,Нижегородская область,Богородский муниципальный район,Командировка,мужской,от 18 до 24 лет,до 30 тыс. руб.,8,6,0.030915
2,22701000,город Нижний Новгород,2021-01-08,Поездка внутри страны,Экскурсант,Россия,Ленинградская область,NaN,Туризм,мужской,от 25 до 34 лет,свыше 100 тыс. руб.,1,3,0.018046
3,22701000,город Нижний Новгород,2021-01-08,Поездка внутри страны,Турист,Россия,Нижегородская область,Богородский муниципальный район,Командировка,мужской,от 35 до 44 лет,от 50 до 70 тыс. руб.,7,5,0.094773
4,22701000,город Нижний Новгород,2021-01-17,Поездка внутри страны,Турист,Россия,Нижегородская область,город Бор,Посещение друзей и родственников,женский,от 35 до 44 лет,до 30 тыс. руб.,3,4,0.008532
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
482233,22701000,город Нижний Новгород,2021-06-14,Поездка внутри страны,Экскурсант,Россия,Ульяновская область,NaN,Туризм,мужской,от 25 до 34 лет,до 30 тыс. руб.,1.0,2.0,0.002012
482234,22701000,город Нижний Новгород,2021-06-10,Поездка внутри страны,Экскурсант,Россия,Рязанская область,NaN,Туризм,мужской,от 55 до 63 лет,от 30 до 50 тыс. руб.,1.0,4.0,0.00948
482235,22701000,город Нижний Новгород,2021-06-22,Поездка внутри страны,Экскурсант,Россия,Нижегородская область,город Кулебаки,Посещение друзей и родственников,мужской,свыше 64 лет,до 30 тыс. руб.,1.0,4.0,0.003579
482236,22701000,город Нижний Новгород,2021-06-23,Поездка внутри страны,Турист,Россия,Республика Дагестан,NaN,Туризм,женский,от 55 до 63 лет,от 50 до 70 тыс. руб.,12.0,2.0,0.099466
482237,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
df[df['days_cnt'] == 'DAYS_CNT']

,territory_code,territory_name,arrival_date,trip_type,visit_type,home_country,home_region,home_city,goal,gender,age_group,income_group,days_cnt,visitors_cnt,spent_mln
69592,TERRITORY_CODE,TERRITORY_NAME,DATE_OF_ARRIVAL,TRIP_TYPE,VISIT_TYPE,HOME_COUNTRY,HOME_REGION,HOME_CITY,GOAL,GENDER,AGE,INCOME,DAYS_CNT,VISITORS_CNT,SPENT
135094,TERRITORY_CODE,TERRITORY_NAME,DATE_OF_ARRIVAL,TRIP_TYPE,VISIT_TYPE,HOME_COUNTRY,HOME_REGION,HOME_CITY,GOAL,GENDER,AGE,INCOME,DAYS_CNT,VISITORS_CNT,SPENT
212484,TERRITORY_CODE,TERRITORY_NAME,DATE_OF_ARRIVAL,TRIP_TYPE,VISIT_TYPE,HOME_COUNTRY,HOME_REGION,HOME_CITY,GOAL,GENDER,AGE,INCOME,DAYS_CNT,VISITORS_CNT,SPENT
287299,TERRITORY_CODE,TERRITORY_NAME,DATE_OF_ARRIVAL,TRIP_TYPE,VISIT_TYPE,HOME_COUNTRY,HOME_REGION,HOME_CITY,GOAL,GENDER,AGE,INCOME,DAYS_CNT,VISITORS_CNT,SPENT
382561,TERRITORY_CODE,TERRITORY_NAME,DATE_OF_ARRIVAL,TRIP_TYPE,VISIT_TYPE,HOME_COUNTRY,HOME_REGION,HOME_CITY,GOAL,GENDER,AGE,INCOME,DAYS_CNT,VISITORS_CNT,SPENT